services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - VITE_MAPBOX_TOKEN=${VITE_MAPBOX_TOKEN}
