FROM node:22

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Exponer el puerto donde preview servirá la app
EXPOSE 4173

# Usar vite preview para servir producción
CMD ["npx", "vite", "preview", "--port", "4173", "--host"]
